### ISSUE TITLE
Add truncate graphs to AGI

### ISSUE THREAD

**Issue by garyday-aerospike** [aerospike/aerolab#193]
It would be good to get a truncate graph added to AGI graphs. Relevant log lines are:
`
Nov 01 2023 13:28:47 GMT: INFO (truncate): (truncate.c:151) {test} got command to truncate to now (436541327298)
Nov 01 2023 13:28:47 GMT: INFO (truncate): (truncate.c:355) {test} truncating to 436541327298 on 4 threads
Nov 01 2023 13:28:47 GMT: INFO (truncate): (truncate.c:464) {test} done truncate to 436541327298 deleted 5
`

**Comment by robertglonek** [comment]
Will implement :) Makes sense to have graphs (well, dots, not lines) for this, representing each truncate run. We can create 2 panels, one with truncate timestamps, and one with deleted(?) Let me know if you think we can do it somehow otherwise with one panel or so, I cannot think of a way (one is plotting a truncation timestamp and one record count).

**Comment by robertglonek** [comment]
Done, will be implemented in 7.2.0
