### ISSUE TITLE
Need the ability to add specific ports to firewall rules

### ISSUE THREAD

**Issue by jdogmcsteezy** [aerospike/aerolab#234]
@hev and I have been testing an application we install on the aerospike node and access via our local machines. The application needs port 5000 exposed. One workaround is to create a firewall rule and use that at cluster creation time but then we lose the ability to lockdown our IP using `discover-caller-ip`

To be fair we could probably just change the port needed in the application to one that is already exposed.

**Comment by robertglonek** [comment]
Example:

```
# create a firewall rule, opening port 5000 and 6000, and no default ports
aerolab config gcp create-firewall-rules -n bob -p 5000 -p 6000 --no-defaults

# allow those ports from the world (yes, specify ports and no-defaults again, or it will be overriden)
# the requirement to re-specify is by design, and allows to fully override a rule once it's created
aerolab config gcp lock-firewall-rules -n bob -p 5000 -p 6000 -i 0.0.0.0/0 --no-defaults

# add the rule to the existing cluster
aerolab cluster add firewall -n cluster --zone us-central1-a --firewall=bob

# add the rule to the existing client
aerolab client configure firewall -n client --zone us-central1-a --firewall=bob
```

Do NOT use `aerolab cluster create --firewall=aerolab-managed-external --firewall=bob` as part of the deployment with such customizations, as this command WILL attempt to relock any firewall rules that are applied to a newly created cluster which may disallow connectivity to deploy said cluster. This is by design to aid easy connectivity for people who’s IPs change frequently who just want it to work without manually managing their firewalls.
